import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getAdminSession } from "@/lib/auth";
import { z } from "zod";
const schema = z.object({ id: z.string().optional(), name: z.string().trim().min(2), type: z.enum(["percentage", "fixed"]), value: z.coerce.number().nonnegative(), startDate: z.string(), endDate: z.string(), productIds: z.string(), active: z.boolean().default(true) });
async function guard() { return Boolean(await getAdminSession()); }
export async function GET() { if (!(await guard())) return NextResponse.json({ error: "Accès administrateur requis." }, { status: 403 }); return NextResponse.json({ promotions: await prisma.promotion.findMany({ orderBy: { startDate: "desc" } }) }); }
export async function POST(request: Request) { if (!(await guard())) return NextResponse.json({ error: "Accès administrateur requis." }, { status: 403 }); const p = schema.omit({ id: true }).safeParse(await request.json()); if (!p.success) return NextResponse.json({ error: "Promotion invalide." }, { status: 400 }); return NextResponse.json({ promotion: await prisma.promotion.create({ data: { ...p.data, startDate: new Date(p.data.startDate), endDate: new Date(p.data.endDate) } }) }, { status: 201 }); }
export async function PATCH(request: Request) { if (!(await guard())) return NextResponse.json({ error: "Accès administrateur requis." }, { status: 403 }); const p = schema.required({ id: true }).safeParse(await request.json()); if (!p.success) return NextResponse.json({ error: "Promotion invalide." }, { status: 400 }); const { id, ...data } = p.data; return NextResponse.json({ promotion: await prisma.promotion.update({ where: { id }, data: { ...data, startDate: new Date(data.startDate), endDate: new Date(data.endDate) } }) }); }
export async function DELETE(request: Request) { if (!(await guard())) return NextResponse.json({ error: "Accès administrateur requis." }, { status: 403 }); const p = z.object({ id: z.string() }).safeParse(await request.json()); if (!p.success) return NextResponse.json({ error: "Promotion invalide." }, { status: 400 }); await prisma.promotion.delete({ where: { id: p.data.id } }); return NextResponse.json({ ok: true }); }
